# Generated by Django 4.2.2 on 2023-06-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(verbose_name='status')),
                ('uri', models.TextField(verbose_name='uri')),
                ('owner', models.CharField(max_length=40, verbose_name='owner')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('price', models.IntegerField(default=0, verbose_name='price')),
                ('image', models.ImageField(upload_to='images/')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='date_of_creation')),
            ],
            options={
                'verbose_name': 'art',
            },
        ),
    ]
