# Generated by Django 4.2.2 on 2023-06-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='owner',
            field=models.CharField(max_length=41, verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='art',
            name='status',
            field=models.IntegerField(choices=[('for sale', 1), ('sold', 0)], default=1, verbose_name='status'),
        ),
    ]
