# Generated by Django 4.2.2 on 2023-06-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_art_owner_alter_art_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='owner',
            field=models.CharField(max_length=42, verbose_name='owner'),
        ),
    ]
